site_name: R Devel Container Docs
repo_name: r-devel/r-dev-env
repo_url: https://github.com/r-devel/r-dev-env
nav:
    - 'Home': 'index.md'
    - 'Container Setup':
        - 'Starting Codespace': 'container_setup/creating_codespace.md'
        - 'Restarting and Stopping' : 'container_setup/codespacestartstop.md'
        - 'Collaborating with Live Share' : 'container_setup/live_share.md'
        - 'Local Setup' : 'container_setup/localsetup.md'
    - 'Tutorials':
        - 'Running R' : 'tutorials/running_r.md'
        - 'Building R': 'tutorials/building_r.md'
        - 'R Contribution Workflow' : 'tutorials/contribution_workflow.md'
        - 'Updating Source Code' : 'tutorials/update_source.md'
        - 'Creating a Patch File' : 'tutorials/patch_update.md'
        - 'Multiple R Versions' : 'tutorials/multi_r_compilation.md'
        - 'SVN Help' : 'tutorials/svn_help.md'
    - 'Contributor Guide' : 
        - 'contributor_guide/contributing_to_docs.md'
        - 'contributor_guide/contributing_to_codebase.md'
    - 'Resources' : 'resources.md'
    - 'Troubleshooting Info' : 'troubleshoot.md'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy


  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: indigo
      accent: blue
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: indigo
      accent: blue

plugins:
  - social

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/r-devel/r-dev-env/
    - icon: fontawesome/brands/slack
      link: https://r-contributors.slack.com/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
