# This workflow uses actions that are not certified by GitHub.  
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.  

name: Build and publish Docker image

on:
  workflow_dispatch:
  pull_request:


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ubdbra001/r-dev-env

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version number
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Log in to the Container registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{ env.VERSION }}
            type=sha

      - name: Build ARM docker image via bash
        run: |
          docker buildx build --progress=plain --platform linux/arm64 -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm_test --build-arg CONTAINER_VERSION=${{ env.VERSION }} .

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Build and push ARM based Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm.${{ github.ref_name }}
          build-args: |
            CONTAINER_VERSION=${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64
